site_name: "MusicalNinjas"

watch:
- recurtools
- pytest-doctest-mkdocstrings

theme:
  name: "material"
  icon:
    logo: material/ninja
  palette: # Palette toggles for auto-light-dark mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/link
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default 
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to system preference
  features:
    - navigation.expand
    - navigation.path
    - navigation.tabs
    - toc.integrate

plugins:
- search
- monorepo
- mkdocstrings:
    handlers:
      python:
        options:
          show_bases: false
          show_root_heading: true
          heading_level: 2
          show_root_full_path: false
          show_symbol_type_toc: true
          show_symbol_type_heading: true
          signature_crossrefs: true
          separate_signature: true
          show_signature_annotations: true
          docstring_section_style: spacy
          docstring_options:
            ignore_init_summary: true
          merge_init_into_class: true

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format

nav:
- recurtools: '!include ./recurtools/mkdocs.yml'
- pytest-doctest-mkdocstrings: '!include ./pytest-doctest-mkdocstrings/mkdocs.yml'
